### ISSUE TITLE
Add a "Get Curent" or "Refresh" Button

### ISSUE THREAD

**Issue by LeoCatsune** [CodeMyst/DeezCord#5]
Sometimes, the status doesn't update itself, and I end out having to restart the app.
Having a button to grab the latest data would be greatly appreciated.

**Comment by CodeMyst** [comment]
Are you use it doesn't update? Since the poll rate is set to 30 seconds if I remember correctly. Also sorry on the late reply, I think my GitHub notifications are broken.
